model_list:
  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: http://openuix-ollama:11434

litellm_settings:
  drop_params: True
  telemetry: False

general_settings: 
  master_key: sk-1234
  store_model_in_db: True

